# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9GNtgOR4mtZuMqDAAmCKNe36Y0Rvmhy
"""

from google.colab import files
archivo_subido = files.upload()

# analisis_datos.py
import pandas as pd
import numpy as np

# -------------------------------
# Ejercicio 1: Análisis de Ventas
# -------------------------------

ventas = pd.read_csv("ventas.csv")

# Crear una categoría según el producto
categorias = {
    'Laptop': 'Electrónica',
    'Mouse': 'Accesorios',
    'Teclado': 'Accesorios',
    'Monitor': 'Electrónica',
    'Celular': 'Electrónica',
    'Silla': 'Muebles',
    'Escritorio': 'Muebles',
    'Audífonos': 'Accesorios',
    'Cámara': 'Electrónica',
    'Impresora': 'Electrónica'
}
ventas['Categoría'] = ventas['Producto'].map(categorias)

# Total de productos vendidos por categoría
ventas_por_categoria = ventas.groupby("Categoría")["Cantidad"].sum()

# Producto con el mayor total de ventas (en dinero)
ventas["TotalVenta"] = ventas["Cantidad"] * ventas["Precio_Unitario"]
producto_mayor_venta = ventas.groupby("Producto")["TotalVenta"].sum().idxmax()

# Precio promedio de los productos vendidos
precio_promedio = ventas["Precio_Unitario"].mean()

print("=== Ejercicio 1: Análisis de Ventas ===")
print("Total vendidos por categoría:\n", ventas_por_categoria)
print("Producto con mayor total de ventas:", producto_mayor_venta)
print("Precio promedio:", round(precio_promedio, 2), "\n")

# ------------------------------
# Ejercicio 2: Análisis del Clima
# ------------------------------

clima = pd.read_csv("clima.csv")

# Temperatura promedio por ciudad
promedio_ciudad = clima.groupby("Ciudad")["Temperatura"].mean()

# Temperatura más alta y más baja
registro_max = clima.loc[clima["Temperatura"].idxmax()]
registro_min = clima.loc[clima["Temperatura"].idxmin()]

# Ciudad con temperatura más alta y más baja
ciudad_max = registro_max["Ciudad"]
ciudad_min = registro_min["Ciudad"]

# Registros con temperatura mayor a 30°C
mayores_30 = clima[clima["Temperatura"] > 30].shape[0]

# Días registrados por ciudad
dias_por_ciudad = clima["Ciudad"].value_counts()

print("=== Ejercicio 2: Análisis del Clima ===")
print("Temperatura promedio por ciudad:\n", promedio_ciudad)
print("Registro más alto:\n", registro_max)
print("Registro más bajo:\n", registro_min)
print("Ciudad más calurosa:", ciudad_max)
print("Ciudad más fría:", ciudad_min)
print("Registros con temperatura > 30°C:", mayores_30)
print("Días registrados por ciudad:\n", dias_por_ciudad, "\n")

# --------------------------------------
# Ejercicio 3: Estadísticas de Calificaciones
# --------------------------------------

# Cargar y corregir encabezado si tiene errores de codificación
calificaciones = pd.read_csv("calificaciones.csv", encoding='latin1')

# Mostrar primeras filas
print("=== Ejercicio 3: Calificaciones ===")
print("Primeras filas:\n", calificaciones.head())

# Promedio por materia
promedio_materia = calificaciones.groupby("Materia")["Calificacion"].mean()
print("Promedio por materia:\n", promedio_materia)

# Agrupar por estudiante y calcular promedio
promedio_estudiante = calificaciones.groupby("Estudiante")["Calificacion"].mean()

# Estudiante con promedio más alto
est_mejor = promedio_estudiante.idxmax()
print("Estudiante con mejor promedio:", est_mejor)

# Estudiantes con promedio > 85
superior_85 = promedio_estudiante[promedio_estudiante > 85].count()
print("Estudiantes con promedio > 85:", superior_85)

# Materia con más calificaciones
materia_frecuente = calificaciones["Materia"].value_counts().idxmax()
print("Materia con más calificaciones:", materia_frecuente)

# 5 estudiantes con el promedio más bajo
peores_5 = promedio_estudiante.nsmallest(5)
print("5 estudiantes con menor promedio:\n", peores_5)